name: Build package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: purcell/setup-emacs@v3.0
        with:
          version: 28.1
      - name: Setup Melpazoid
        run: |
          git clone https://github.com/riscy/melpazoid.git ~/melpazoid
          pip install ~/melpazoid
      - name: Scan, byte-compile and sanity check package
        env:
          LOCAL_REPO: ${{ github.workspace }}
          RECIPE: (mos-mode :repo "themkat/mos-mode" :fetcher github)
          EXIST_OK: false
        run: |
          make -C ~/melpazoid
